### ISSUE TITLE
Typescript Enum (converted to primitive number) as binding value raises TypeError in tracer

### ISSUE THREAD

**Issue by joma74** [TiagoMestre/inversify-tracer#2]
**Versions**
"inversify-tracer": "^1.0.7"
"inversify": "^3.0.0-rc.4"

**StackTrace**
`
TypeError: Cannot create property 'toString' on number '2'
    at methods.forEach (node_modules/inversify-tracer/lib/src/proxy.js:37:32)
    at Array.forEach (native)
    at ProxyListener.apply (node_modules/inversify-tracer/lib/src/proxy.js:34:17)
    at InversifyTracer.applyToBinding (node_modules/inversify-tracer/lib/src/tracer.js:46:39)
    at bindings.forEach (node_modules/inversify-tracer/lib/src/tracer.js:65:22)
    at Array.forEach (native)
    at container._bindingDictionary._map.forEach (node_modules/inversify-tracer/lib/src/tracer.js:64:22)
    at Map.forEach (native)
    at InversifyTracer.applyToContainer (node_modules/inversify-tracer/lib/src/tracer.js:63:43)
    at InversifyTracer.apply (node_modules/inversify-tracer/lib/src/tracer.js:40:25)
    at Context.<anonymous> (lib/test/diinversify/configs/DIInversify.Configs.spec.js:41:20)
`

**Description**
Case is `container.bind<EnvEnum>(EnvEnum.TYPE.NAME).toConstantValue(EnvEnum.PROD);` which works w/o inversify-tracer as expected. 
Typescript `export enum EnvEnum {
    DEV,
    MOCK,
    PROD
}` is finally js-converted to numbers. EnvEnum.PROD to number 2.
With inversify-tracer that the above StackTrace is raised.

**Comment by TiagoMestre** [comment]
This error was caused because I wasn't filtering the values created by the container. Tracer will only be applied to Objects (not including Array).

The version 1.0.8 should have fixed this issue.

Can you confirm the fix?

**Comment by joma74** [comment]
Fixed with 1.0.8.
Thank you :grinning:
